// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonMusic: typeof import('~icons/carbon/music')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/Footer.vue')['default']
    ItemRecipes: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/items/components/ItemRecipes.vue')['default']
    ItemsTable: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/items/components/ItemsTable.vue')['default']
    Itemtile: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/items/components/itemtile.vue')['default']
    ItemTile: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/items/components/ItemTile.vue')['default']
    PlanItem: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/items/components/PlanItem.vue')['default']
    README: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/README.md')['default']
    VButton: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/VButton.vue')['default']
    VButtonText: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/VButtonText.vue')['default']
    VDescription: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/VDescription.vue')['default']
    VInput: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/VInput.vue')['default']
    VTitleLg: typeof import('C:/Users/tjswl/project/LoLpago-1/src/main/front/src/common/components/VTitleLg.vue')['default']
  }
}

export { }
